### PR TITLE
fix reserve unitedDeployment

### LINKED ISSUE #83: [feature request]please reserve UnitedDeployment resource for version compatibility.
**What would you like to be added**:
We should reserve UnitedDeployment resource in yurt-app-manager for one or two versions time, not rename it to YurtAppSet.

**Why is this needed**:
If end user is using UnitedDeployment, but UnitedDeployment disappeared suddenly, end users maybe fell confused and can not keep the compatibility for original workloads. 

**others**
/kind feature

### PR DESCRIPTION
**Pull request by hxcGit**
Signed-off-by: hxcGit <houxc_mail@163.com>

#### What this PR does / why we need it:
We should reserve UnitedDeployment resource in yurt-app-manager for one or two versions time, not just rename it to YurtAppSet.

#### Which issue(s) this PR fixes:

Fixes #83, #62 

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by huiwq1990** [comment]
@hxcGit the crd should put in chart directory too.

**Comment by rambohe-ch** [comment]
@hxcGit please update valid and mutate webhook for UnitedDeployment, and you can reference the newest webhook of other controllers in yurt-app-manager.

**Comment by hxcGit** [comment]
@huiwq1990 @rambohe-ch  How can I add `uniteddeployment` in  `charts/yurt-app-manager/templates/admission-webhooks/mutatingwebhookconfiguration.yaml` and `charts/yurt-app-manager/templates/admission-webhooks/validatingwebhookconfiguration.yaml`? 

Is there any command to do this automatically? Or I can add it manually?

**Comment by rambohe-ch** [comment]
> @huiwq1990 @rambohe-ch How can I add `uniteddeployment` in `charts/yurt-app-manager/templates/admission-webhooks/mutatingwebhookconfiguration.yaml` and `charts/yurt-app-manager/templates/admission-webhooks/validatingwebhookconfiguration.yaml`?
> 
> Is there any command to do this automatically? Or I can add it manually?

@hxcGit Maybe you should add it manually.

**Comment by rambohe-ch** [comment]
@huiwq1990 Please take a look.

**Comment by hxcGit** [comment]
@rambohe-ch @huiwq1990  
image

For deprecated warning, do you have any suggestions?

Maybe we can follow 
`Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition`

**Comment by rambohe-ch** [comment]
> @rambohe-ch @huiwq1990 image
> 
> For deprecated warning, do you have any suggestions?
> 
> Maybe we can follow `Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition`

@hxcGit yes, we will deprecate `UnitedDeployment` in v0.7.0, and unavailable in v1.1, only keep `UnitedDeployment` in two versions for compatability.

**Comment by huiwq1990** [comment]
> > @huiwq1990 @rambohe-ch How can I add `uniteddeployment` in `charts/yurt-app-manager/templates/admission-webhooks/mutatingwebhookconfiguration.yaml` and `charts/yurt-app-manager/templates/admission-webhooks/validatingwebhookconfiguration.yaml`?
> > Is there any command to do this automatically? Or I can add it manually?
> 
> @hxcGit Maybe you should add it manually.

yes, chart should edit manually.

**Comment by huiwq1990** [comment]
@hxcGit increate the chart version at `charts/yurt-app-manager/Chart.yaml`, it will release a new version at https://github.com/openyurtio/openyurt-helm.

**Comment by hxcGit** [comment]
> @hxcGit increate the chart version at `charts/yurt-app-manager/Chart.yaml`, it will release a new version at https://github.com/openyurtio/openyurt-helm.

https://github.com/openyurtio/yurt-app-manager/blob/a1226f54cca9a9ead65dac8ff6b9eb49bfbda902/charts/yurt-app-manager/Chart.yaml#L18

change to `version: 0.1.2`?

**Comment by huiwq1990** [comment]
> > @hxcGit increate the chart version at `charts/yurt-app-manager/Chart.yaml`, it will release a new version at https://github.com/openyurtio/openyurt-helm.
> 
> https://github.com/openyurtio/yurt-app-manager/blob/a1226f54cca9a9ead65dac8ff6b9eb49bfbda902/charts/yurt-app-manager/Chart.yaml#L18
> 
> change to `version: 0.1.2`?

it's ok.

**Comment by rambohe-ch** [comment]
@hxcGit because codecov is reduced, we can not merge this pull request. maybe you need to make some unit tests for UnitedDeployment.

**Comment by hxcGit** [comment]
> @hxcGit because codecov is reduced, we can not merge this pull request. maybe you need to make some unit tests for UnitedDeployment.

@rambohe-ch  I found that most of the functions in `UnitedDeployment Controller` rely on a K8s cluster. And I can't use `sigs.k8s.io/controller-runtime/pkg/envtest` library in github action. Do you have any suggestions?

**Comment by rambohe-ch** [comment]
> > @hxcGit because codecov is reduced, we can not merge this pull request. maybe you need to make some unit tests for UnitedDeployment.
> 
> @rambohe-ch I found that most of the functions in `UnitedDeployment Controller` rely on a K8s cluster. And I can't use `sigs.k8s.io/controller-runtime/pkg/envtest` library in github action. Do you have any suggestions?

@hxcGit It looks like the unit test coverage has increased now, so i will merge this pull request.

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
