### PR TITLE
crd naming optimization

### PR DESCRIPTION
**Pull request by YTGhost**
Signed-off-by: HIHIA <283304489@qq.com>

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
crd naming optimization
#### Which issue(s) this PR fixes:

Fixes https://github.com/openyurtio/openyurt/issues/852

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@zzguang PTAL

**Comment by zzguang** [comment]
Generally, it looks good to me except one word of "ingressIps", I am not sure whether "ingressIPs" is better, please check it, thanks!

**Comment by YTGhost** [comment]
> Generally, it looks good to me except one word of "ingressIps", I am not sure whether "ingressIPs" is better, please check it, thanks!

Yep, you're right. Please take another look

**Comment by zzguang** [comment]
@YTGhost ， Since the CRD naming is optimized, could you please update the related doc accordingly? Thanks!

**Comment by YTGhost** [comment]
> @YTGhost ， Since the CRD naming is optimized, could you please update the related doc accordingly? Thanks!

ok

**Comment by YTGhost** [comment]
> @YTGhost ， Since the CRD naming is optimized, could you please update the related doc accordingly? Thanks!

Hi, I'm not very familiar with it, so I'd like to ask if it refers to the documentation here？https://github.com/openyurtio/openyurt.io

**Comment by rambohe-ch** [comment]
> > @YTGhost ， Since the CRD naming is optimized, could you please update the related doc accordingly? Thanks!
> 
> Hi, I'm not very familiar with it, so I'd like to ask if it refers to the documentation here？https://github.com/openyurtio/openyurt.io

@YTGhost yes, all official documents are hosted in this repo, and can be accessed from website: https://openyurt.io.

**Pull request merged**
