### PR TITLE
support k8s 1.22

### PR DESCRIPTION
**Pull request by huiwq1990**
/kind feature
> /kind question
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage

#### What this PR does / why we need it:

support k8s 1.22, it should cooperate with https://github.com/openyurtio/openyurt/pull/809

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by zzguang** [comment]
@huiwq1990 YurtIngress source code has been updated to add some enhancement features, could you please update this PR based on the latest source code? Sorry for the code conflict.

**Comment by huiwq1990** [comment]
@zzguang Already fix it.

**Comment by zzguang** [comment]
Hi, @huiwq1990 :
@adamzhoul submitted a PR to support k8s 1.22 for yurt-app-manager as well: https://github.com/openyurtio/yurt-app-manager/pull/56
I checked both of your PRs and found that your changes differ much with each other, so could you please cross review with @adamzhoul and submit an unified PR after your discussion? Thanks!

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
