### PR TITLE
crd naming additional modifications

### PR DESCRIPTION
**Pull request by YTGhost**
Signed-off-by: HIHIA <283304489@qq.com>

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
After https://github.com/openyurtio/yurt-app-manager/pull/117, I found that some of the yaml files also need to be updated

#### Which issue(s) this PR fixes:

Fixes https://github.com/openyurtio/openyurt/issues/852

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@zzguang PTAL

**Comment by Congrool** [comment]
We seems to use `make generate-deploy-yaml` to generate yamls for all crds. Do you modify it manually or use the make command? @YTGhost 

By the way, do we still use `all-in-one.yaml` to install yurt-app-manager? PTAL @huiwq1990

**Comment by YTGhost** [comment]
> We seems to use `make generate-deploy-yaml` to generate yamls for all crds. Do you modify it manually or use the make command? @YTGhost
> 
> By the way, do we still use `all-in-one.yaml` to install yurt-app-manager? PTAL @huiwq1990

Yep, I use `make generate-deploy-yaml` to generate yamls for all crds, and then use the content to modify these two files.

**Comment by luc99hen** [comment]
> We seems to use `make generate-deploy-yaml` to generate yamls for all crds. Do you modify it manually or use the make command? @YTGhost
> 
> By the way, do we still use `all-in-one.yaml` to install yurt-app-manager? PTAL @huiwq1990

We recommend to use helm instead of yaml in the latest documentation.

**Comment by luc99hen** [comment]
> Since
> 
> > We recommend to use helm instead of yaml in the latest documentation.
> 
> should we continue to maintain all-in-one.yaml in the following version?
I think they are no longer needed. What do you think of it? @rambohe-ch please

**Comment by zzguang** [comment]
Since helm chart will replace the old yaml file style, it may not need to maintain the yaml file any more, please double check it.
Besides, for YurtIngress, the related docs need to be updated accordingly:
1. The proposal doc:
https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20210628-nodepool-ingress-support.md
2. The user tutorial doc:
https://github.com/openyurtio/openyurt.io/blob/master/versioned_docs/version-v1.1/user-manuals/network/edge-ingress.md
https://github.com/openyurtio/openyurt.io/blob/master/i18n/zh/docusaurus-plugin-content-docs/version-v1.1/user-manuals/network/edge-ingress.md
For the related crd naming optimization PRs are assumed to be merged into version v1.1, so I set the version to v1.1 as above.

**Comment by rambohe-ch** [comment]
> We seems to use `make generate-deploy-yaml` to generate yamls for all crds. Do you modify it manually or use the make command? @YTGhost
> 
> By the way, do we still use `all-in-one.yaml` to install yurt-app-manager? PTAL @huiwq1990

@Congrool agree +1, it's not need to maintain `all-in-one.yaml` file for each repos, and if end user want to get yaml files, they will be suggested to get yaml files from helm charts.

**Comment by rambohe-ch** [comment]
@YTGhost I think you can post another pr for removing `all-in-one.yaml` file.

**Comment by YTGhost** [comment]
> @YTGhost I think you can post another pr for removing `all-in-one.yaml` file.

ok

**Comment by YTGhost** [comment]
> Since helm chart will replace the old yaml file style, it may not need to maintain the yaml file any more, please double check it. Besides, for YurtIngress, the related docs need to be updated accordingly:
> 
> 1. The proposal doc:
>    https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20210628-nodepool-ingress-support.md
> 2. The user tutorial doc:
>    https://github.com/openyurtio/openyurt.io/blob/master/versioned_docs/version-v1.1/user-manuals/network/edge-ingress.md
>    https://github.com/openyurtio/openyurt.io/blob/master/i18n/zh/docusaurus-plugin-content-docs/version-v1.1/user-manuals/network/edge-ingress.md
>    For the related crd naming optimization PRs are assumed to be merged into version v1.1, so I set the version to v1.1 as above.

ok，Thanks

**Comment by YTGhost** [comment]
@zzguang PTAL, now I just modify yaml of chart, I will remove `all-in-one.yaml` file in another pr.

**Comment by rambohe-ch** [comment]
@zzguang PTAL

**Pull request merged**
