### PR TITLE
add yurtingress controller unit test

### PR DESCRIPTION
**Pull request by Rudolf1998**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by zzguang** [comment]
@Rudolf1998 , the current unit test coverage is only about 18.8% basing on your PR, which can not meet the 70% target, could you please optimize it to improve the ratio? thanks!
$go test ./pkg/yurtappmanager/controller/yurtingress/... --covermode=count
ok  	github.com/openyurtio/yurt-app-manager/pkg/yurtappmanager/controller/yurtingress	(cached)	coverage: 18.8% of statements

**Comment by kadisi** [comment]
> @Rudolf1998 , the current unit test coverage is only about 18.8% basing on your PR, which can not meet the 70% target, could you please optimize it to improve the ratio? thanks! $go test ./pkg/yurtappmanager/controller/yurtingress/... --covermode=count ok github.com/openyurtio/yurt-app-manager/pkg/yurtappmanager/controller/yurtingress (cached) coverage: 18.8% of statements

@zzguang I think 70% test coverage for the entire `yurt-app-manager `repo is enough, and some unit tests will need mock tests, which we can implement uniformly later.

**Comment by zzguang** [comment]
> > @Rudolf1998 , the current unit test coverage is only about 18.8% basing on your PR, which can not meet the 70% target, could you please optimize it to improve the ratio? thanks! $go test ./pkg/yurtappmanager/controller/yurtingress/... --covermode=count ok github.com/openyurtio/yurt-app-manager/pkg/yurtappmanager/controller/yurtingress (cached) coverage: 18.8% of statements
> 
> @zzguang I think 70% test coverage for the entire `yurt-app-manager `repo is enough, and some unit tests will need mock tests, which we can implement uniformly later.

Okay, agree with you to implement the mock test in future.

**Comment by kadisi** [comment]
@Rudolf1998 please check ci/golangci-lint error info .

**Comment by Congrool** [comment]
Fixes #76

**Review by zzguang — APPROVED** [review]

**Pull request merged**
