### PR TITLE
build and push image when merge master

### PR DESCRIPTION
**Pull request by huiwq1990**
Signed-off-by: huiwq1990 <huiwq1990@163.com>

#### Which issue(s) this PR fixes:

Fixes #https://github.com/openyurtio/yurt-app-manager/issues/91

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@huiwq1990 The ability to periodically build yurt-app-manager image has been implemented, you can reference link here: https://github.com/openyurtio/yurt-app-manager/blob/master/.github/workflows/release.yaml

The image for master branch will be built everyday, the result is here: https://github.com/openyurtio/yurt-app-manager/actions/workflows/release.yaml

**Comment by huiwq1990** [comment]
I want to add a `on.push` master worflow. Currently, the release job not support.

**Review by rambohe-ch — APPROVED** [review]

**Review by rambohe-ch — APPROVED** [review]

**Comment by rambohe-ch** [comment]
fixes #91

**Pull request merged**
